### ISSUE TITLE
Carrios Studio link is broken

### ISSUE THREAD

**Issue by thunder-coding** [mozilla/Fira#243]
The says that the link says "404 Page not found"

**Comment by vrajpatel9988** [comment]
I Want to work with this project.

**Comment by binyamin** [comment]
The new URL seems to be https://bboxtype.com/typefaces/FiraSans/. The page [carrois.com/about](https://carrois.com/about/) points to the [bboxtype.com](https://bboxtype.com) foundry, for the work on typefaces.

**Comment by binyamin** [comment]
Fixed by #240

**Comment by birbilis** [comment]
but fix never merged? I still see broken link in readme for:
Further information on the design and specifications of the Fira typeface can be found at [Carrois Studio](https://carrois.com/typefaces/FiraSans/).
