### ISSUE TITLE
Cannot select Fira Mono as monospaced font under KDE

### ISSUE THREAD

**Issue by houserockr** [mozilla/Fira#56]
I am running KDE on OpenSuSE 13.1.
Within almost any font chooser dialog, I cannot select Fira Mono (TTF Version 3.111) as a monospaced font, although the font is installed and selectable in LibreOffice, for instance.

I've played around with fontforge a bit. It doesn't complain about having different advances or something. It does however complain about erroneous minima/maxima.

Is there any workaround that enables me to select that font?

**Comment by schriftgestalt** [comment]
@houserockr could you send me a monospace font that works for you. I don't have KDE to test so I would at least need a font to compare it to.

**Comment by carrois** [comment]
Hi Houserockr.

Please try these files. 
https://www.dropbox.com/sh/si29c78emoyr2f1/AAB4ZCjMop_5lOiYNyX6IC4Ua?dl=0

We eliminated the nonspacing accents from export.
They might have been the problem as Glyphs sets them to zero width when exporting.
Could you please report?

Please don’t use these file for other purposes by now as we work on an official update of Fira Mono in which we would like include your feedback.
This Test version is still buggy due to new anchor behaviour of Glyphs 2. Thanks!

**Comment by jfkthame** [comment]
Untested hypothesis: I suspect this may well be a symptom of the xAvgCharWidth error described in issue 47. Fixing that might allow KDE to recognize the font as being monospaced.

If that's the case, the test version above ought to work, as it has xAvgCharWidth=600.

**Comment by houserockr** [comment]
Hey there, thank you very much for addressing this issue!
Unfortunately, I'm on vacation right now, so I can't test it on KDE.
However, I tested it on OSX, where it works like a charm!
I can test KDE next week, if this fits with whatever deadlines you have!?

**Comment by carrois** [comment]
There’s no rush, Mono 4.0 won’t be released in the next weeks. Romans and Italics first.
Thanks for reporting after your vacaction.

**Comment by houserockr** [comment]
Tested it on Kubuntu 14.10 with the new KDE plasma 5.2 --> working!
I would still like to test it next week on the plattform I reported...

**Comment by houserockr** [comment]
Also works on KDE 4, OpenSuSE 13.1 (platform reported)!
Thank you!

**Comment by wolftune** [comment]
I'm confused about the status of this. I downloaded the latest Fira Mono 3.2 from this repo, and I'm not able to select Fira Mono in Yakuake. Is the fix not actually released yet?

**Comment by patrykdesign** [comment]
Fira Mono 3.2 should have the fix. @houserockr can you help @wolftune in anyway? Not sure what you did to get it working?

**Comment by houserockr** [comment]
I have to say that I haven't tested version 3.2. I only tested the "-KDE" version above, which I am still using since my test.

Here's what I did to install the font:
`$ cp font.ttf ~/.fonts/`
`$ fc-cache -r`

**Comment by jfkthame** [comment]
It looks like there are a couple of glyphs in the Fira Mono 3.2 fonts that still don't have the correct advance width; check "fraction" (U+2044) and "uni2215" (division slash). This is probably what prevents some applications accepting the fonts as "monospaced".

While here, I also noticed that there are discrepancies between the .ttf and .otf versions of the fonts: they don't contain identical OpenType layout tables, as I would have expected. It looks like they were generated from slightly different versions of the source, which is rather unfortunate as it will lead to unexpected and confusing differences in behavior.

**Comment by carrois** [comment]
Hi Jonathan.

I'll forward this mail to Georg.

> Am 11.05.2015 um 16:21 schrieb jfkthame <notifications@github.com>:
> 
> It looks like there are a couple of glyphs in the Fira Mono 3.2 fonts that still don't have the correct advance width; check "fraction" (U+2044) and "uni2215" (division slash). This is probably what prevents some applications accepting the fonts as „monospaced".
> 
> 
We talkes a lot with Georg concerning this issue and thought it is fixed.

> While here, I also noticed that there are discrepancies between the .ttf and .otf versions of the fonts: they don't contain identical OpenType layout tables, as I would have expected. It looks like they were generated from slightly different versions of the source, which is rather unfortunate as it will lead to unexpected and confusing differences in behavior
> 
> 

No, all files came from the same source.
Think this is a Glyphs issue, too.

Will answer ASAP.
_r

**Comment by jfkthame** [comment]
In the new Fira Mono 3.201 there are still a few glyphs with an incorrect width: in a quick search of the Regular face, at least, I found

    <mtx name="uni045F" width="603" lsb="100"/>
    <mtx name="uni1F69" width="582" lsb="-79"/>
    <mtx name="uni1FA9" width="582" lsb="-79"/>

In Fira Mono Bold, on the other hand, I found

    <mtx name="uni045F" width="575" lsb="70"/>

and in Medium, it's

    <mtx name="uni045F" width="592" lsb="89"/>

As long as there are *any* glyphs with a width other than 600 or zero, the "monospaced" nature of the fonts will remain broken.

**Comment by jfkthame** [comment]
The issue with OpenType layout discrepancies between OTF and TTF fonts is still present. I've opened a new issue for this, as it's unrelated to the glyph width variations.

**Comment by carrois** [comment]
I have to apologize for that.
Mono are files updated already.
Please download again.
_r

**Comment by jfkthame** [comment]
Yes, that looks better! Thanks.

(I have not tested this in KDE/OpenSuSE etc, as in the original report, but AFAICS from the font data it should now be fixed.)

**Comment by patrykdesign** [comment]
OK will close this as it should be fixed. @houserockr let me know otherwise.

**Comment by wolftune** [comment]
@patrykdesign The mono files in the OTF directory haven't been updated since April 9th. How could this be fixed, given that I reopened this later than that? My best guess is that people made fixes elsewhere, but nobody has merged the fixes to the actual master files.

**Comment by patrykdesign** [comment]
@wolftune @houserockr my bad we were testing 3.203 which contains bug fixes, somehow they didn't make it to the repo, so I just added them, sorry. There's 3.204 coming as in a couple of weeks BTW.

**Comment by wolftune** [comment]
Thanks, the new update is recognized for me in KDE

**Comment by patrykdesign** [comment]
Great thanks!

**Comment by schriftgestalt** [comment]
I’m still trying to figure this out properly. I installed Fedora 22 (not sure what Desktop). I could not find a place where my fonts didn't work. So could you please check if this fonts work as expected? 
https://dl.dropboxusercontent.com/u/3563666/FiraMonoTest.zip
Thanks.

**Comment by jfkthame** [comment]
From a brief check, I don't see any problems in the fonts from FiraMonoTest.zip. Both .ttf and .otf files look as expected.
